---
title: Functies maken en aanroepen in Python
hero_image: images/banner.png
description: Leer hoe je een functie maakt en aanroept
original_url:
theme: cc-prototype
listed: false
duration: 1
ingredient: true
copyedit: true
interests:
technologies: "python"
steps:
  - title: Eenvoudige functies
