title: generic-python-simple-functions
hero_image: images/banner.png
subtitle: generic-python-simple-functions subtitle
description: generic-python-simple-functions description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: Step one
    duration: 60
