title: Creating and calling functions in Python
hero_image: images/banner.png
description: Learn how to create and call a function
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
ingredient: true
steps:
  - title: Step one

