title: Creating and calling functions in Python
hero_image: images/banner.png
description: Learn how to create and call a function
original_url:
theme: cc-prototype
listed: false
duration: 1
ingredient: true
copyedit: true
interests:
technologies: "python"
steps:
  - title: Simple funtions
