---
title: Python में फ़ंक्शन बनाना और कॉल करना
hero_image: images/banner.png
description: फ़ंक्शन बनाना और कॉल करना सीखें
original_url:
theme: cc-prototype
listed: false
duration: 1
ingredient: true
copyedit: true
interests:
technologies: "python"
steps:
  - 
    title: साधारण फ़ंक्शन
