---
title: Creando y llamando funciones en Python
hero_image: images/banner.png
description: Aprende cómo crear y llamar a una función
original_url:
theme: cc-prototype
listed: false
duration: 1
ingredient: true
copyedit: true
interests:
technologies: "python"
steps:
  - title: Funciones simples
