---
title: Créer et appeler des fonctions dans Python
hero_image: images/banner.png
description: Apprendre à créer et à appeler une fonction
original_url:
theme: cc-prototype
listed: false
duration: 1
ingredient: true
copyedit: true
interests:
technologies: "python"
steps:
  - 
    title: Fonctions simples
